
[34m[1mtrain: [39m[22mWARNING: No labels found in /home/pc/workspace/dataset/coco2017/labels/train2017.cache. See https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
[34m[1mtrain: [39m[22mScanning '/home/pc/workspace/dataset/coco2017/labels/train2017' for images and labels... 0 found, 123287 missing, 0 empty, 0 corrupted: 100%|â–ˆ| 123287/123287 [00:16<00:00, 7268
Traceback (most recent call last):
  File "scripts/train.py", line 527, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "scripts/train.py", line 189, in train
    image_weights=opt.image_weights, quad=opt.quad, prefix=colorstr('train: '))
  File "/home/pc/workspace/torch_ws/innox_ws/2D_seg_ws/yolov5_seg/flexible-yolov5/od/data/datasets.py", line 71, in create_dataloader
    prefix=prefix)
  File "/home/pc/workspace/torch_ws/innox_ws/2D_seg_ws/yolov5_seg/flexible-yolov5/od/data/datasets.py", line 381, in __init__
    cache, exists = self.cache_labels(cache_path, prefix), False  # cache
  File "/home/pc/workspace/torch_ws/innox_ws/2D_seg_ws/yolov5_seg/flexible-yolov5/od/data/datasets.py", line 495, in cache_labels
    torch.save(x, path)  # save for next time
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/pc/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/pc/workspace/dataset/coco2017/labels/train2017.cache'